;--------------------------------------------------------------------------------------------
; User Options

[Variables]

;-----------------------
; LAYOUT

Stylesheet=Metro

ColorImage=W

;-----------------------
; GENERAL

Note1Path=C:\Users\%USERNAME%\Dropbox\Action\Tasks.txt
Note2Path=C:\Users\%USERNAME%\Dropbox\Action\Notes.txt
Note3Path=C:\Users\%USERNAME%\Dropbox\Action\About.txt
NoteHeight=160

Drive1=C
Drive2=E
Drive3=F

NetworkMaxDownload=1000000
NetworkMaxUpload=500000
maxDownload=1000000
maxUpload=500000

SystemGraphType=Floating

VolumeIncrement=5

TriptychInterval=30
TriptychDisabled=1
ProcessInterval=5

;-----------------------
; WEATHER
City=Leawood
Zipcode=USKS0638
WeatherURL=http://xml.weather.com/weather/local/#Zipcode#?cc=*&dayf=6
