

;----------------------------------------------
; GRAPH FRAME


[StyleGraphFrameOutline]
;SolidColor=#colorPink#
X=12
Y=12
W=80
H=30

[StyleGraphFrameCpu]
SolidColor=#colorBlue#

[StyleGraphFrameMemory]
SolidColor=#colorPurple#

[StyleGraphFrameHdd]
SolidColor=#colorGreen#

[StyleGraphFrameNet]
SolidColor=#colorBrown#

[StyleGraphFrameInner]
SolidColor=#colorWhite#
X=2r
Y=2r
W=76
H=26

;-----------------------
; GRAPH METERS

[StyleSystemGraph]
AntiAlias=1
X=14
Y=14
W=76
H=26

[StyleSystemGraphCpu]
PrimaryColor=#colorBlueTrans#

[StyleSystemGraphMemory]
PrimaryColor=#colorPurpleTrans#

[StyleSystemGraphLine]
LineCount=1
LineWidth=1
AutoScale=0
AntiAlias=1
X=14
Y=14
W=76
H=26
SolidColor=#colorGrayLighter60#
LineStart=Right

;-----------------------
; LABEL METERS

[StyleTextStat]
StringAlign=left
FontFace=#fontMain#
FontSize=10
AntiAlias=1
ClipString=0


[StyleTextStatLabel]
StringAlign=left
FontColor=#colorGrayDarker#
FontSize=10
StringStyle=bold
AntiAlias=1
ClipString=0
X=100
Y=10


[StyleTextStatValue]
StringAlign=left
FontSize=8
AntiAlias=1
ClipString=0
x=r
y=-2R

[StyleTextStatValue2]
StringAlign=left
FontSize=8
AntiAlias=1
ClipString=0
x=R
y=r


[StyleLabelCpu]
FontColor=#colorBlue#

[StyleLabelMemory]
FontColor=#colorPurple#

[StyleLabelHdd]
FontColor=#colorGreen#

[StyleLabelNet]
FontColor=#colorMagenta#


;-------------------------------------------------------------



[StyleGraphBorder]

[StyleGraphBorderTop]

[StyleGraphBorderRight]

[StyleGraphBorderBottom]

[StyleGraphBorderLeft]




[StyleGraphBorderCpu]



[StyleSystemNormalTop]
X=0
Y=0
W=0
H=0

[StyleSystemNormalVerticalBorderC]
X=0
Y=0
W=0
H=0
Hidden=1

[StyleSystemNormalBorder4]
X=0
Y=0
W=0
H=0
Hidden=1

[StyleSystemNormalBorder5]
X=0
Y=0
W=0
H=0
Hidden=1

;-----------------------
; GRAPH METERS

[StyleSystemNormalGraph]
X=0
Y=0
W=0
H=0
Hidden=1

[StyleSystemNormalGraph1]

[StyleSystemNormalGraph2]