

;----------------------------------------------
; GRAPH FRAME


[StyleGraphFrameOutline]
;SolidColor=#colorPink#
X=12
Y=12
W=80
H=30

[StyleGraphFrameCpu]
SolidColor=#colorBlue#

[StyleGraphFrameInner]
SolidColor=#colorWhite#
X=2r
Y=2r
W=76
H=26

;-----------------------
; GRAPH METERS

[StyleSystemGraph]
AntiAlias=1
AutoScale=1
X=14
Y=14
W=76
H=26

[StyleSystemGraphCpu]
PrimaryColor=#colorBlue#

;-----------------------
; LABEL METERS

[StyleTextStat]
StringAlign=left
FontFace=#fontMain#
FontSize=10
AntiAlias=1
ClipString=0


[StyleTextStatLabel]
StringAlign=left
FontColor=#colorBlueTrans#
FontSize=10
StringStyle=bold
AntiAlias=1
ClipString=0
X=100
Y=10


[StyleTextStatValue]
StringAlign=left
FontColor=#colorBlue#
FontSize=8
AntiAlias=1
ClipString=0
x=r
y=-2R

[StyleTextStatValue2]
StringAlign=left
FontColor=#colorBlue#
FontSize=8
AntiAlias=1
ClipString=0
x=R
y=r

;-------------------------------------------------------------



[StyleGraphBorder]

[StyleGraphBorderTop]

[StyleGraphBorderRight]

[StyleGraphBorderBottom]

[StyleGraphBorderLeft]




[StyleGraphBorderCpu]



[StyleSystemNormalTop]
X=0
Y=0
W=0
H=0

[StyleSystemNormalVerticalBorderC]
X=0
Y=0
W=0
H=0
Hidden=1

[StyleSystemNormalBorder4]
X=0
Y=0
W=0
H=0
Hidden=1

[StyleSystemNormalBorder5]
X=0
Y=0
W=0
H=0
Hidden=1

;-----------------------
; GRAPH METERS

[StyleSystemNormalGraph]
X=0
Y=0
W=0
H=0
Hidden=1

[StyleSystemNormalGraph1]

[StyleSystemNormalGraph2]