;--------------------------------------------------------------------------------------------
; COMMON VARIABLES AND STYLES

[Variables]

; colors
; --------------------------------------------------

; windows metro colors

colorBlue=27,161,226
colorBlueTrans=27,161,226,200

colorPurple=104,72,201
colorMagenta=255,0,151
colorTeal=0,171,169
colorLime=140,191,38
colorBrown=160,80,0
colorPink=230,113,184
colorOrange=240,150,9
colorRed=229,20,0
colorGreen=51,153,51

colorPurpleTrans=104,72,201,200
colorMagentaTrans=255,0,151,200
colorTealTrans=0,171,169,200
colorLimeTrans=140,191,38,200
colorBrownTrans=160,80,0,200
colorPinkTrans=230,113,184,200
colorOrangeTrans=240,150,9,200
colorRedTrans=229,20,0,200
colorGreenTrans=51,153,51,200

;Grays
colorBlack=0,0,0
colorGrayDarker=34,34,34
colorGrayDark=51,51,51
colorGray=85,85,85
colorGrayLight=153,153,153
colorGrayLighter=238,238,238
colorWhite=255,255,255
colorWhiteTrans=255,255,255,200

colorSemiTransparent=255,255,255,125
colorTransparent=255,255,255,2

colorSkyBlueDark=9,74,178
colorSkyBlueLight=10,91,196

colorGrayLight80=153,153,153,204
colorGrayLighter80=238,238,238,204
colorGrayLighter60=238,238,238,150


; Typography
; --------------------------------------------------

fontMain=Segoe UI
fontSegoe=Segoe UI

fontCaviar=Caviar Dreams
fontUbuntu=Ubuntu

FontSize12=12
FontSize10=10
FontSize9=9
FontSize8=8
FontSize7=7


; Backgrounds
; --------------------------------------------------

SkinBackgroundAlpha=60
HideBordersTop=1
HideBordersBottom=1


; Sidebar
; --------------------------------------------------

SidebarWidth=220
SidebarSpacingFixed=1
SidebarAlpha=120
SidebarImage=#@#Images\Sidebar.#ColorImage#.png
;SidebarImage=#@#Images\Sidebar\Sidebar.#ColorImage#.png
;SidebarImage=#@#Images\Sidebar.Glass.Blue.png


